# ----
# Site

title: CloudFx
description: CloudFx is a non-profit developers community - "for developers of developers".
url: https://cloudfx.github.io/
disqus_shortname: cloudfxcommunity
theme: jekyll-theme-cloudfx
baseurl:

current_youtube: C43MYopI7c0

active_sibling: Home
main_url: ""
google_site_verification: GkBrJRSQqF43wQVGLUeUJFTPBldtIXGCw9toqvS2o_o
permalink: pretty
collections:
  webinars:
    output: true
    permalink: /webinars/:title/
  messages:
    output: false
    permalink: /messages/:name/
defaults:
  - scope:
      path: ""
    values:
      header_class: "short"
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      _options:
        content:
          uploads_dir: "images/blog/:title"
          format: p h2 h3 h4 h5 h6
          link: true
          removeformat: true
          bold: true
          italic: true
          image: true
          numberedlist: true
          bulletedlist: true
          code: true
          styles: "src/css/editor.css"
        image:
          upload_dir: "images/blog/:title"
          
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-data

# ----------
# SEO plugin

lang: en_US
logo: /siteicon.png
twitter:
  username: cl0udfx
facebook:
  publisher: https://www.facebook.com/CloudFx-231724584101177
social:
  name: CloudFx
  links:
    - https://twitter.com/cl0udfx
    - https://www.facebook.com/CloudFx-231724584101177
    - https://plus.google.com/u/1/103074069812013806852
    - https://www.youtube.com/channel/UCV4TwSmiwW-NlgMGI8zIb6Q
    - https://github.com/CloudFx

footer:
  contact_us:
    email: cloudfxcommunity@gmail.com
  copyright: CloudFx Community
  social:
    twitter: cl0udfx
    facebook: CloudFx-231724584101177
    google: u/1/103074069812013806852
    youtube: UCV4TwSmiwW-NlgMGI8zIb6Q

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json

recaptcha:
  sitekey: 6Lfng1EUAAAAAIqcLgzGcjRjVHR46BbyqZNgU2Xd
  
_options:
  content:
    format: p h2 h3 h4 h5 h6
    link: true
    removeformat: true
    bold: true
    italic: true
    image: true
    numberedlist: true
    bulletedlist: true
    code: true
    styles: "css/editor.css"